[build-system]
requires = ["setuptools>=64", "setuptools_scm>=8"]

[project]
name = "pelican_migration"
version = "0.0.1-alpha"
authors = [
    { name="Simon Roy" },
]
description = "A modern migration tool for SQLAlchemy."
readme = "README.md"
license = { file="LICENSE" }
requires-python = ">=3.12"

dependencies = [
    "sqlalchemy",
    "click",
]

[project.optional-dependencies]
dev = [
    "pytest",
    "black",
    "mypy",
]

[project.urls]
"Source" = "https://github.com/PenguinBoi12/pelican"

[project.scripts]
pelican = "pelican.cli:cli"

[tool.setuptools]
packages = ["pelican"]
license-files = []

[tool.mypy]
exclude = ['pelican/templates']