import re

_TYPE_ALIASES: list[tuple[str, str]] = [
    # Must come before shorter aliases that would partial-match
    (r"CHARACTER VARYING", "VARCHAR"),
    # Bare VARCHAR (no length) is unbounded text — normalize to TEXT so SQLModel's
    # AutoString (str fields) matches TEXT columns generated by t.text()
    (r"^VARCHAR$", "TEXT"),
    (r"DOUBLE PRECISION", "DOUBLE"),
    (r"TIMESTAMP WITHOUT TIME ZONE", "TIMESTAMP"),
    (r"TIMESTAMP WITH TIME ZONE", "TIMESTAMPTZ"),
    (r"FLOAT8\b", "DOUBLE"),
    (r"FLOAT4\b", "REAL"),
    (r"\bINT4\b", "INTEGER"),
    (r"\bINT8\b", "BIGINT"),
    (r"\bINT2\b", "SMALLINT"),
    # INT alone but not INTERVAL, INTEGER, etc.
    (r"\bINT\b", "INTEGER"),
    (r"\bBOOL\b", "BOOLEAN"),
    # Strip MySQL-style display widths that carry no semantic meaning
    (r"INTEGER\(\d+\)", "INTEGER"),
    (r"BIGINT\(\d+\)", "BIGINT"),
    (r"SMALLINT\(\d+\)", "SMALLINT"),
]

_COMPILED_ALIASES = [(re.compile(p), r) for p, r in _TYPE_ALIASES]

_TYPE_CAST = re.compile(r"::[a-z][a-z0-9 ]*", re.IGNORECASE)
_WHITESPACE = re.compile(r"\s+")
_QUOTED_IDENTIFIER = re.compile(r'"(\w+)"')
_OUTER_PARENS = re.compile(r"^\((.+)\)$", re.DOTALL)


def normalize_type(type_str: str) -> str:
    s = type_str.strip().upper()
    for pattern, replacement in _COMPILED_ALIASES:
        s = pattern.sub(replacement, s)
    return s


def normalize_server_default(expr: str) -> str:
    s = expr.strip()
    # Strip type casts before anything else: 'active'::character varying → 'active'
    s = _TYPE_CAST.sub("", s)
    # Strip one layer of outer parens Postgres wraps defaults in
    m = _OUTER_PARENS.match(s)
    if m:
        s = m.group(1).strip()
    # Lowercase and collapse whitespace
    s = _WHITESPACE.sub(" ", s.lower()).strip()
    # Normalize boolean literals
    s = re.sub(r"'true'|'\s*1\s*'", "true", s)
    s = re.sub(r"'false'|'\s*0\s*'", "false", s)
    return s


def normalize_check_expression(expr: str) -> str:
    s = expr.strip()
    # Strip one outer paren layer Postgres adds around check expressions
    m = _OUTER_PARENS.match(s)
    if m:
        s = m.group(1).strip()
    # Remove quotes around plain identifiers: "age" → age
    s = _QUOTED_IDENTIFIER.sub(r"\1", s)
    # Lowercase and collapse whitespace
    s = _WHITESPACE.sub(" ", s.lower()).strip()
    return s
